### ISSUE TITLE
Should we switch from alligator to celery?

### ISSUE THREAD

**Issue by groovecoder** [mdn/webalyzer#14]
[Alligator's WHY?!!1!](https://pypi.python.org/pypi/alligator/0.10.0) seems like a bad basis for a task queue system? Any reason we couldn't or shouldn't use celery instead?

**Comment by peterbe** [comment]
Yes. But I would suggest to wait. Alligator might not be as powerful and mature as some of the more established alternatives, but that doesn't matter if nobody is using it.

**Comment by groovecoder** [comment]
:+1:
