### ISSUE TITLE
Change collect.js to do nothing and have "event hooks"

### ISSUE THREAD

**Issue by peterbe** [mdn/webalyzer#23]
Instead of just doing `<script src="webalyzer.domain/collect.js" data-domain="mydomain"></script>`
The user would do:

```
<script src="webalyzer.domain/collect.js"></script>
<script>
Webalyzer.configure('mydomain', {
    doSend: function(url) {
        return Math.random() > 0.7;
    }
});
```

**Comment by peterbe** [comment]
e.g. make it similar to GA.

**Comment by stephaniehobson** [comment]
This is what GA is recommending these days:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-36116321-5', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by stephaniehobson** [comment]
Things we might want to let the users config:
- whether or not to collect text content (we could strip all text nodes from page before sending)
- how often to check for changes and resend (ie, if they have a static site, no need to re-send, if it's a single page app this might be pretty high)
- URL patterns to exclude (ie, maybe not to run collector on areas with PPI)

**Comment by peterbe** [comment]
Sorry for sounding lazy byt all of those can be "outsourced" to the user of the script by passing through a function of their own making. For example, 

``` javascript
shuffle = function(s) {
   var a = s.split(""),
        n = a.length;
    for(var i = n - 1; i > 0; i--) {
        var j = Math.floor(Math.random() * (i + 1));
        var tmp = a[i];
        a[i] = a[j];
        a[j] = tmp;
    }
    return a.join("");
}
Webalyzer.configure('mydomain', {
    beforeSendHTML: function(html) {
        return html.replace(/>([^<]+<)/g, shuffle)
    }
});
```

That's a silly example, but that way webalyzer can stay out of the game at this early start.

**Comment by peterbe** [comment]
So, a couple of questions. 
- What should we call the module/object? `Webalyzer` or `webalyzer` or `collectalyzer` or `mdnservices`? Google Analytics calls theirs `ga`. 
- Considering that the domain can be automatically extracted from `document.location.hostname` it might be silly to **force** people to have to say `Webalyzer.configure('mydomain')`. But it certainly should be something you can override. 
- How about you simply trigger it by initializing it. E.g. `Webalyzer({domain: 'mydomain.com', doSend: myfunction, sendCSS: false})` would be enough to start it noticing and sending HTML (and CSS). 
- Some people might have their .png and .css always publicly available on a public DNS. These people might not want us to collect CSS and images because the server can download them later (if it even needs them). They might want to set `sendCSS: false` and `sendImages: false` as possible options.
- What if I sign in to Webalyzer to preemptively set up a configuration that I'm going to use. If I did, and I get a unique token, I'd be able to do something like `Webalyzer({key: 'ae3001fee28cf918a'})` I'd be able to use this on `http://localhost:8000` when I do local development. 
- Other possible events I can imaging:...
  -  `doSend(html, url)` - so you can decide to NOT collect based on some business logic
  - `beforeSendHTML(html)` - a chance to mess with the HTML before it gets sent
  - `afterSendHTML(html, collected)` - a callback after the AJAX POST

**Comment by peterbe** [comment]
How about?

``` html
<script>
(var s = document.createElement('script'); 
 s.src = 'https://webalyzer.heroku.com/collect.js'; 
 document.head.appendChild(s); s.async=true; s.onload=function() {
    Webalyzer({domain: 'example.com'});
})();
</script>
```

I haven't tested it yet but it's relatively compact, async and convenient indentation which makes it clear where to stuff in your own configuration options. 

Whichever we do, sadly, we might need to test this in IE.
